import Link from "next/link";
import { LockRound } from "@/components/contextual-quorum-actions";
import { screenings, summary } from "@/lib/data-source";

export default async function RoundPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const [sum, rows] = await Promise.all([summary(id), screenings(id)]);
  if (sum.kind !== "AVAILABLE") return <main className="qc-shell"><Link href="/rounds">← Rounds</Link><h1 className="qc-display">Round not found</h1></main>;
  const pending = Number(sum.value.pending); const requested = Number(sum.value.requested); const lockDisabled = sum.value.status !== "OPEN" || !requested || pending > 0;
  const lockReason = sum.value.status !== "OPEN" ? "This round is already locked or screening." : !requested ? "Request at least one screening before locking the round." : pending > 0 ? "Resolve all pending screenings before locking the round." : undefined;
  return <main className="qc-shell"><Link className="qc-link" href="/rounds">← Rounds</Link><header className="qc-round-header"><span className="qc-label">ROUND {sum.value.id}</span><h1 className="qc-display">{sum.value.name}</h1><p>{sum.value.status} · {sum.value.coi_start_year} to {sum.value.coi_end_year}, closed calendar-year window. {sum.value.reviewers.length} reviewers × {sum.value.applicants.length} applicants.</p></header><nav className="qc-nav"><Link href={`/rounds/${id}/participants`}>Participants</Link><Link href={`/rounds/${id}/scope`}>Evidence scope</Link><Link href={`/rounds/${id}/screenings`}>Screenings</Link></nav><section className="qc-card mt-6"><h2 className="qc-heading">Round controls</h2><p className="qc-note mt-2">Locking freezes the review set and weight calculation. It is available only after requested screenings are no longer pending.</p><LockRound roundId={id} disabled={lockDisabled} reason={lockReason} /></section><div className="qc-table-wrap mt-6"><table className="qc-table"><thead><tr><th>Reviewer</th><th>Applicant</th><th>Finding</th><th>Weight</th><th>Evidence</th></tr></thead><tbody>{rows.kind === "AVAILABLE" ? rows.value.map((row) => <tr key={row.id}><td className="qc-record">{row.reviewer}</td><td className="qc-record">{row.applicant}</td><td><span className={`qc-badge qc-${row.status.toLowerCase()}`}>{row.status}</span><p className="qc-note">{row.rationale || "Not screened yet."}</p></td><td className="qc-record">{row.weight_bp} bp</td><td className="qc-note">{row.tie_basis || "No tie named"}<br />{row.sources_failed ? `Failed: ${row.sources_failed}` : "Sources answered"}</td></tr>) : <tr><td colSpan={5}>Screenings unavailable: {rows.kind === "UNAVAILABLE" || rows.kind === "INVALID_RESPONSE" ? rows.error : "not found"}</td></tr>}</tbody></table></div></main>;
}
