import Link from "next/link";
import { ScreeningRequest, ScreeningRun } from "@/components/contextual-quorum-actions";
import { bond, screenings, summary } from "@/lib/data-source";
import { pairKey } from "@/lib/contract-types";
import { formatGen } from "@/lib/format";

export default async function ScreeningsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const [sum, rows, bondResult] = await Promise.all([summary(id), screenings(id), bond()]);
  if (sum.kind !== "AVAILABLE") return <main className="qc-shell"><Link className="qc-link" href="/rounds">← Rounds</Link><h1 className="qc-display">Screenings unavailable</h1><p className="qc-alert">{sum.kind === "NOT_FOUND" ? "This round does not exist." : sum.error}</p></main>;
  const existing = rows.kind === "AVAILABLE" ? new Map(rows.value.map((row) => [pairKey(row.reviewer, row.applicant), row])) : new Map();
  const bondWei = bondResult.kind === "AVAILABLE" ? bondResult.value : "0";
  const pairs = sum.value.reviewers.flatMap((reviewer) => sum.value.applicants.map((applicant) => ({ reviewer, applicant, row: existing.get(pairKey(reviewer, applicant)) })));
  return <main className="qc-shell"><Link className="qc-link" href={`/rounds/${id}`}>← Round overview</Link><header className="qc-round-header"><span className="qc-label">SCREENINGS · {id}</span><h1 className="qc-display">Evidence findings</h1><p>Each pair is resolved only from sources that answered. A missing source cannot improve a result to CLEAR. The current screening bond is {formatGen(bondWei)}.</p></header>{rows.kind !== "AVAILABLE" ? <p className="qc-alert">Screening records unavailable: {rows.kind === "NOT_FOUND" ? "not found" : rows.error}</p> : pairs.length ? <div className="grid gap-4">{pairs.map(({ reviewer, applicant, row }) => <article className="qc-card" key={`${reviewer}:${applicant}`}><div className="flex flex-wrap items-baseline justify-between gap-3"><h2 className="qc-heading">{reviewer.slice(0, 10)}… × {applicant.slice(0, 10)}…</h2><span className={`qc-badge qc-${(row?.status ?? "UNSCREENED").toLowerCase()}`}>{row?.status ?? "NOT REQUESTED"}</span></div>{row ? <><p className="qc-note mt-3">{row.rationale || "No rationale recorded."}</p><ScreeningRun screeningId={row.id} status={row.status} /></> : <><p className="qc-note mt-3">No screening has been requested for this pair.</p><ScreeningRequest roundId={id} reviewer={reviewer} applicant={applicant} bondWei={bondWei} /></>}</article>)}</div> : <section className="qc-card"><h2 className="qc-heading">No reviewer × applicant pairs yet</h2><p className="qc-note mt-2">Register at least one reviewer and applicant before requesting screening.</p><div className="mt-3 flex gap-4"><Link className="qc-link" href={`/rounds/${id}/participants`}>Add participants →</Link><Link className="qc-link" href={`/rounds/${id}/scope`}>Declare scope →</Link></div></section>}</main>;
}
