import Link from "next/link";
import { AppealForm, ScreeningRun } from "@/components/contextual-quorum-actions";
import { bond, screening } from "@/lib/data-source";
export const dynamic = "force-dynamic";

export default async function ScreeningPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const [result, bondResult] = await Promise.all([screening(decodeURIComponent(id)), bond()]);
  if (result.kind !== "AVAILABLE") return <main className="qc-shell"><Link className="qc-link" href="/rounds">← Rounds</Link><h1 className="qc-display">Screening unavailable</h1><p className="qc-alert">{result.kind === "NOT_FOUND" ? "No screening record exists for this id." : result.error}</p></main>;
  const row = result.value;
  return <main className="qc-shell"><Link className="qc-link" href={`/rounds/${row.round_id}/screenings`}>← Round screenings</Link><header className="qc-round-header"><span className="qc-label">SCREENING EVIDENCE</span><h1 className="qc-display">{row.status}</h1><p>{row.reviewer} × {row.applicant} · round {row.round_id}</p></header><section className="qc-card"><h2 className="qc-heading">Outcome</h2><p className="mt-2">{row.status === "CLEAR" ? "No publicly evidenced tie was found in the sources that answered." : row.rationale || "No final verdict is recorded."}</p><p className="qc-record mt-2">Weight: {row.weight_bp} bp</p><div className="mt-4"><ScreeningRun screeningId={row.id} status={row.status} /></div></section><section className="qc-card mt-4"><h2 className="qc-heading">Source completeness</h2><p className="qc-note mt-2">Answered: {row.sources_checked || "none recorded"}</p><p className="qc-note">Unavailable: {row.sources_failed || "none recorded"}</p><details className="mt-3"><summary>Technical evidence</summary><p className="qc-record mt-2">Digest: {row.evidence_digest || "none recorded"}</p><p>{row.tie_basis || "No tie named"}</p><p>{row.link_basis || "No identity link recorded"}</p></details></section><section className="qc-card mt-4"><h2 className="qc-heading">Appeal</h2>{row.appeal_id ? <Link className="qc-link" href={`/appeals/${encodeURIComponent(row.appeal_id)}`}>Open appeal {row.appeal_id} →</Link> : <AppealForm screeningId={row.id} bondWei={bondResult.kind === "AVAILABLE" ? bondResult.value : "0"} />}</section></main>;
}
